/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "on-tertiary-fixed": "#001f26",
            "tertiary": "#4cd7f6",
            "surface-container-low": "#191b23",
            "on-secondary-fixed-variant": "#38485d",
            "surface": "#10131a",
            "secondary-fixed-dim": "#b7c8e1",
            "secondary-container": "#3a4a5f",
            "inverse-primary": "#005ac2",
            "on-primary": "#002e6a",
            "surface-variant": "#32353c",
            "on-tertiary-container": "#002f38",
            "on-primary-fixed-variant": "#004395",
            "primary": "#adc6ff",
            "tertiary-container": "#009eb9",
            "on-surface-variant": "#c2c6d6",
            "on-secondary-container": "#a9bad3",
            "on-secondary-fixed": "#0b1c30",
            "surface-dim": "#10131a",
            "tertiary-fixed": "#acedff",
            "tertiary-fixed-dim": "#4cd7f6",
            "primary-fixed-dim": "#adc6ff",
            "secondary": "#b7c8e1",
            "on-secondary": "#213145",
            "primary-container": "#4d8eff",
            "outline-variant": "#424754",
            "on-primary-container": "#00285d",
            "surface-container-highest": "#32353c",
            "primary-fixed": "#d8e2ff",
            "on-surface": "#e1e2ec",
            "on-error": "#690005",
            "on-tertiary": "#003640",
            "secondary-fixed": "#d3e4fe",
            "surface-bright": "#363941",
            "error": "#ffb4ab",
            "on-primary-fixed": "#001a42",
            "on-tertiary-fixed-variant": "#004e5c",
            "on-background": "#e1e2ec",
            "surface-container-lowest": "#0b0e15",
            "surface-tint": "#adc6ff",
            "error-container": "#93000a",
            "background": "#10131a",
            "inverse-surface": "#e1e2ec",
            "on-error-container": "#ffdad6",
            "surface-container-high": "#272a31",
            "inverse-on-surface": "#2e3038",
            "surface-container": "#1d2027",
            "outline": "#8c909f"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        "spacing": {
            "gutter": "24px",
            "2xl": "48px",
            "3xl": "64px",
            "unit": "4px",
            "xs": "4px",
            "sm": "8px",
            "md": "16px",
            "xl": "32px",
            "margin": "32px",
            "lg": "24px"
        },
        "fontFamily": {
            "headline-lg": ["Space Grotesk"],
            "mono-data": ["Space Grotesk"],
            "display-xl": ["Space Grotesk"],
            "headline-md": ["Space Grotesk"],
            "label-caps": ["Inter"],
            "body-md": ["Inter"],
            "body-sm": ["Inter"],
            "body-lg": ["Inter"]
        },
        "fontSize": {
            "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
            "mono-data": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
            "display-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
            "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
            "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
            "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
            "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
            "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
        }
    },
  },
  plugins: [],
}
